source 'https://github.com/Carota-MarketPlanner/podspecs.git'

platform :ios, '15.0'
use_frameworks!

target 'CarotaTheme-Example' do
  pod 'CarotaTheme/Source', :path => '../'
  
  pod 'CDSComponents/Source', '1.0.1'

end
