source 'https://github.com/Carota-MarketPlanner/Specs.git'

platform :ios, '15.0'
use_frameworks!

target 'CarotaTheme-Example' do
  pod 'CarotaTheme/Source', :path => '../'
  
  pod 'CDSComponents', '1.0.6'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 15.0
      end
    end
  end
end
