source 'git@github.com:Carota-MarketPlanner/Specs.git'

platform :ios, '15.0'
use_frameworks!

target 'CarotaTheme-Example' do
  pod 'CarotaTheme/Source', :path => '../'
  
  pod 'CDSComponents', '1.0.4'

end
