name: Build And Test

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit